### ISSUE TITLE
groupId/artifactId in readme

### ISSUE THREAD

**Issue by toddbaert** [splitio/split-openfeature-provider-java#2]
Hey Split!

First of all, amazing job with the provider. It looks great. Even the readme is beautiful.

I was wondering if it made sense to mention the `groupId/artifactId` of the artifact in the readme, or even add an example `<dependency>...</dependency>` element. Apologies if this is mentioned elsewhere and I somehow missed it.

Thanks again!

**Comment by patricioe** [comment]
I think it does. We'll add it!

**Comment by rgrassian-split** [comment]
Thanks for bringing it up @toddbaert! We added it now (and I subscribed to notifications so we won't reply months later next time an issue is created)
